export enum ProfileApplicationErrors {
    CURRENT_PASSWORD_NOT_PRESENT = "CURRENT_PASSWORD_NOT_PRESENT",
    NEW_PASSWORD_NOT_PRESENT = "NEW_PASSWORD_NOT_PRESENT",
    NEW_PASSWORD_TOO_SHORT = "NEW_PASSWORD_TOO_SHORT",
    NEW_PASSWORD_REQUIRES_UPPERCASE = "NEW_PASSWORD_REQUIRES_UPPERCASE",
    NEW_PASSWORD_REQUIRES_NUMBER = "NEW_PASSWORD_REQUIRES_NUMBER",
    NEW_PASSWORD_REQUIRES_SYMBOL = "NEW_PASSWORD_REQUIRES_SYMBOL",
    NEW_PASSWORD_CONFIRMATION_NOT_PRESENT = "NEW_PASSWORD_CONFIRMATION_NOT_PRESENT",
    NEW_PASSWORD_CONFIRMATION_TOO_SHORT = "NEW_PASSWORD_CONFIRMATION_TOO_SHORT",
    PASSWORD_CONFIRMATION_MISMATCH = "PASSWORD_CONFIRMATION_MISMATCH",
}
