export enum ActionType {
    USER_REGISTERED,
    USER_VERIFICATION,
    REQUEST_VERIFICATION_CODE,
    PASSWORD_RESET,
    SUBSCRIPTION_THANK_YOU,
    TRIAL_ENDING_SOON,
    PASSWORD_CHANGED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_REACTIVATED
}