import EmailTemplateContentDatasource from "@admin/emailTemplates/Data/Datasources/EmailTemplateContentDatasource";
import IEmailTemplateContentRepository from "@admin/emailTemplates/Domain/Repositories/IEmailTemplateContentRepository";
import EmailTemplateContentRepositoryImpl from "@admin/emailTemplates/Data/Repositories/EmailTemplateContentRepositoryImpl";
import { IGetEmailTemplateContentUseCase } from "@admin/emailTemplates/Application/UseCases/GetEmailTemplateContent/IGetEmailTemplateContentUseCase";
import GetEmailTemplateContentUseCaseImpl from "@admin/emailTemplates/Application/UseCases/GetEmailTemplateContent/GetEmailTemplateContentUseCaseImpl";

const contentDatasource: EmailTemplateContentDatasource = new EmailTemplateContentDatasource();
const contentRepository: IEmailTemplateContentRepository = new EmailTemplateContentRepositoryImpl(contentDatasource);
const getTemplateContentUseCase: IGetEmailTemplateContentUseCase = new GetEmailTemplateContentUseCaseImpl(contentRepository);

export default getTemplateContentUseCase;