
import EmailTemplateSettingsRepositoryImpl from "@admin/emailTemplates/Data/Repositories/EmailTemplateSettingsRepositoryImpl";
import EmailTemplatesSettingsDatasource from "@admin/emailTemplates/Data/Datasources/EmailTemplatesSettingsDatasource";
import ISaveTemplateForActionUseCase from "@admin/emailTemplates/Application/UseCases/SaveTemplateForAction/ISaveTemplateForActionUseCase";
import SaveTemplateForActionUseCaseImpl from "@admin/emailTemplates/Application/UseCases/SaveTemplateForAction/SaveTemplateForActionUseCaseImpl";
import IEmailTemplateSettingsRepository from "@admin/emailTemplates/Domain/Repositories/IEmailTemplateSettingsRepository";


const datasource: EmailTemplatesSettingsDatasource = new EmailTemplatesSettingsDatasource();
const repository: IEmailTemplateSettingsRepository = new EmailTemplateSettingsRepositoryImpl(datasource);
const SaveTemplateForActionUseCase: ISaveTemplateForActionUseCase = new SaveTemplateForActionUseCaseImpl(repository);

export default SaveTemplateForActionUseCase;