export enum EventsErrors {
    UNAUTHORIZED = "UNAUTHORIZED",
    NETWORK_ERROR = "NETWORK_ERROR",
    CREATE_FAILED = "CREATE_FAILED",
    GENERAL_ERROR = "GENERAL_ERROR",
    LIST_FAILED = "LIST_FAILED",
    DELETE_FAILED = "DELETE_FAILED",
    TOGGLE_STATUS_FAILED = "TOGGLE_STATUS_FAILED",
}
