export enum RecordingsErrors {
    UNAUTHORIZED = "UNAUTHORIZED",
    NETWORK_ERROR = "NETWORK_ERROR",
    UPLOAD_FAILED = "UPLOAD_FAILED",
    GENERAL_ERROR = "GENERAL_ERROR",
    LIST_FAILED = "LIST_FAILED",
    DELETE_FAILED = "DELETE_FAILED",
}
