export enum RecordingsApplicationErrors {
    NAME_REQUIRED = "NAME_REQUIRED",
    DESCRIPTION_REQUIRED = "DESCRIPTION_REQUIRED",
    TYPE_REQUIRED = "TYPE_REQUIRED",
    FILE_REQUIRED = "FILE_REQUIRED",
    FILE_NAME_REQUIRED = "FILE_NAME_REQUIRED",
}

