export enum CatalogErrors {
  UNAUTHORIZED = "UNAUTHORIZED",
  NETWORK_ERROR = "NETWORK_ERROR",
  NOT_FOUND = "NOT_FOUND",
  FETCH_FAILED = "FETCH_FAILED",
  CREATE_PRICE_FAILED = "CREATE_PRICE_FAILED",
  TOGGLE_FAILED = "TOGGLE_FAILED",
  GENERAL_ERROR = "GENERAL_ERROR",
}
