export enum AuthApplicationErrors {
    FULL_NAME_NOT_PRESENT = 'FULL_NAME_NOT_PRESENT',
    FULL_NAME_TOO_SHORT = 'FULL_NAME_TOO_SHORT',
    EMAIL_NOT_PRESENT = 'EMAIL_NOT_PRESENT',
    EMAIL_INVALID = 'EMAIL_INVALID',
    PASSWORD_NOT_PRESENT = 'PASSWORD_NOT_PRESENT',
    PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
    VERIFICATION_CODE_NOT_PRESENT = 'VERIFICATION_CODE_NOT_PRESENT',
    VERIFICATION_CODE_TOO_SHORT = 'VERIFICATION_CODE_TOO_SHORT'
}