export enum EventsApplicationErrors {
    NAME_REQUIRED = "NAME_REQUIRED",
    DESCRIPTION_REQUIRED = "DESCRIPTION_REQUIRED",
    DATE_REQUIRED = "DATE_REQUIRED",
    DURATION_REQUIRED = "DURATION_REQUIRED",
    TIMEZONE_REQUIRED = "TIMEZONE_REQUIRED",
    PRICE_REQUIRED = "PRICE_REQUIRED",
    CURRENCY_REQUIRED = "CURRENCY_REQUIRED",
}
